bot/urls.py
# This file contains all the API endpoints of the bot Django app
from django.urls import path

from . import views

app_name = "bot"
urlpatterns = [

    # ---------------------- PAGES ----------------------
    # ex: /bot/
    path("", views.redirect_view),

    # ex: /bot/register/
    path("register/", views.user_registration, name="user_registration"),
    # ex: /bot/chat/5/
    path("chat/<int:user_id>/", views.conversation, name="conversation"),

    # ex: /bot/users/
    path("users/", views.UsersView.as_view(), name="users"),
    # ex: /bot/users/5/
    # we use pk to use the default Django DetailView
    path("users/<int:pk>/", views.DetailView.as_view(), name="user_details"),
    # ex: /bot/users/vegetarian/
    path("users/<str:nutrition>/", views.nutrition_users, name="nutrition_users"),

    # ex: /bot/users/vegetarian/api/
    path("users/<str:nutrition>/api/", views.UsersNutritionList.as_view(), name="nutrition_users_api"),

    # ---------------------- ACTIONS ----------------------    
    # ex: /bot/start_conversation/
    path("start_conversation/", views.start_conversation, name="start_conversation"),

    # ex: /bot/response/5/
    path("response/<int:user_id>/", views.response, name="response"),
    
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import redirect_view 

urlpatterns = [
    path("", redirect_view),
    path("admin/", admin.site.urls),
    path('api/auth/', include('rest_framework.urls')),
    path("bot/", include("bot.urls")),
]

bot/models.py
# This file contains all the database models of the app 
from django.db import models

class FoodCategory(models.Model):
    name = models.CharField(max_length=10)

    class Meta:
        constraints = [
            # We don't allow multiple FoodCategory objects with the same name
            models.UniqueConstraint(fields=["name"], name="unique Food Category")
        ]

    def __str__(self):
        return self.name
    
class Food(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(FoodCategory, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            # We don't allow multiple Food objects with the same name
            models.UniqueConstraint(fields=["name"], name="unique Food")
        ]
    
    def __str__(self):
        return self.name

class User(models.Model):
    name = models.CharField(max_length=200)
    favorite_foods = models.ManyToManyField(Food, blank=True, related_name="liked_by")
    nutrition = models.ForeignKey(FoodCategory, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def calculate_nutrition(self):
        """
        Calculates the nutrition category from the user based on his/her top 3 favorite foods
        """
        # If he/she likes a food that only Omnivore people can eat -> he/she will be Omnivore
        if len([food for food in list(self.favorite_foods.all()) if food.category.name == "Omnivore"]):
            self.nutrition, _ = FoodCategory.objects.get_or_create(name="Omnivore")

        # If the previous one is not true and he/she likes a food that only Vegetarian people can eat -> he/she will be Vegetarian
        elif len([food for food in list(self.favorite_foods.all()) if food.category.name == "Vegetarian"]):
            self.nutrition, _ = FoodCategory.objects.get_or_create(name="Vegetarian")

        # Otherwise he/she only likes food that Vegan people can eat -> so he/she will be vegetarian
        else:
            self.nutrition, _ = FoodCategory.objects.get_or_create(name="Vegan")
        
        return self.nutrition.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Stages/questions of the conversation
    CONVERSATION_QUESTIONS = {
        "1" : "NAME",
        "2" : "FOOD",
        "3" : "END"
    }
    conversation_stage = models.CharField(max_length=4, choices=CONVERSATION_QUESTIONS)

    # Owner of the message
    OWNER = {
        "USR" : "User",
        "BOT" : "Bot"
    }
    owner = models.CharField(max_length=4, choices=OWNER)

    message = models.CharField(max_length=200)

    def __str__(self):
        return self.message

bot/views.py
# This file contains all the views from the bot Django app
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from rest_framework.views import APIView
from rest_framework.views import Response
from rest_framework import permissions

import json

from bot.models import FoodCategory, Food, User, Message
from bot.openAIcalls import *

# ---------------------- PAGES ----------------------

def redirect_view(request):
    """
    View to redirect to another url.
    This view is called when the url is "/bot". So being in "/bot" will redirect you to the given url.
    """
    response = redirect('/bot/register/')
    return response


def user_registration(request):
    """
    View that renders the page where the user register himself/herself by writing his/her name
    """
    return render(request, "bot/register.html")


def conversation(request, user_id):
    """
    View that renders the page of the conversation with the chatbot.
    Obtains all the messages form the user with the id sent as a parameter and they will be displayed in the page.
    """

    # Getting the messages from the user passed as parameter
    messages = list(Message.objects.filter(user__id = user_id))

    return render(request, "bot/chat.html", {"user_id" : user_id, "messages" : messages})

class UsersView(generic.ListView):
    template_name = "bot/users.html"
    context_object_name = "current_users"

    def get_queryset(self):
        """Return the last five published questions."""
        return User.objects.all()


def nutrition_users(request, nutrition):
    """
    View that shows a list of all the users with the nutrition given as a parameter
    """
    current_users = User.objects.filter(nutrition__name=nutrition)
    context = {
        "current_users": current_users,
        "nutrition": nutrition,
    }
    return render(request, "bot/users.html", context)

class DetailView(generic.DetailView):
    """
    Default django view that shows the details of a user
    """
    model = User
    template_name = "bot/user_details.html"


# ---------------------- ACTIONS ----------------------

def start_conversation(request):
    """
    View that initiates a conversation: 
        1. creates a user
        2. creates the first question from the bot
    It is called when the button in the user_registration is pressed
    """
    # we get the userName from the form input divs, using the name parameter values to access them
    user_name = request.POST['userName']

    # create a user
    user = User.objects.create(name=user_name)

    # obtaining and storing question about the user top 3 favorite foods question
    favorite_foods_question = favorite_food_question_prompt(name=user.name)

    Message.objects.create(user=user, conversation_stage=Message.CONVERSATION_QUESTIONS["2"], owner=Message.OWNER["BOT"], message=favorite_foods_question[:200])

    return HttpResponseRedirect(reverse("bot:conversation", args=(user.id,)))


def response(request, user_id):
    """
    View that processes the user message and gives and answer
        1. Gets the user message from the POST dictionary
        2. Creates a Message object to store the message
        3. Identify the foods mentioned in the message
        4. Creates a Food object and obtains its category if the food hadn't been mentioned before by another user
        5. Adds the food to the favorite foods of the user
        6. Calculates the user nutrition type
        7. Stores a message with the answer from the bot

    It is called when the user sends a message
    """

    # we get the message from the form input divs, using the name parameter values to access them
    use_message = request.POST['message']
    user = User.objects.get(pk=user_id)

    Message.objects.create(user=user, conversation_stage=Message.CONVERSATION_QUESTIONS["2"], owner=Message.OWNER["USR"], message=use_message[:200])

    # identify and storing foods in user answer
    foods_json = identify_food_prompt(message=use_message)

    for food in json.loads(foods_json)["foods"]:
        food_obj, created = Food.objects.get_or_create(name=food)
        if created:
            category = identify_food_category_prompt(food=food_obj.name)

            food_obj.category = FoodCategory.objects.get(name=category)
            food_obj.save()

        # Adding the Food object in the ManyToMany field
        user.favorite_foods.add(food_obj)
    
    # Calculating the nutrition category of the user based on his/her top 3 favorite foods
    user.calculate_nutrition()
    user.save()

    bot_answer = f"It looks like you are {user.nutrition}!"
    Message.objects.create(user=user, conversation_stage=Message.CONVERSATION_QUESTIONS["3"], owner=Message.OWNER["BOT"], message=bot_answer[:200])

    return HttpResponseRedirect(reverse("bot:conversation", args=(user.id,)))

class UsersNutritionList(APIView):
    """
    View that returns all the users with  the nutrition given as parameter
    """
    permission_classes = [permissions.IsAuthenticated]
    def get(self, request, nutrition):

        users = []
        for u in User.objects.filter(nutrition__name=nutrition):
            users.append({'name' : u.name, 'favorite_foods' : [f.name for f in u.favorite_foods.all()]})

        return Response(users)

bot/templates/bot/chat.html
<!-- This file is contains the HTML code that renders the page with the chatbot interface. -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chatbot</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            height: 100vh;
        }

        .chat-container {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            height: 100%;
        }

        .title {
            background-color: #F0F2F5;
            color: #111B21;
            text-align: center;
            padding: 10px;
            font-size: 20px;
        }

        .messages {
            flex-grow: 1;
            padding: 10px;
            overflow-y: auto;
            background-color: #EFEAE2;
        }

        .message {
            margin: 5px 0;
            padding: 10px;
            border-radius: 10px;
            max-width: 50%;
        }

        .message.Bot {
            background-color: #FFFFFF;
            text-align: left;
            margin-left: 10px;
        }

        .message.User {
            background-color: #D9FDD3;
            text-align: right;
            margin-left: auto;
            margin-right: 10px;
        }

        .input-container {
            display: flex;
            flex-direction: row;
            padding: 10px;
            background-color:#F0F2F5;
            border-top: 1px solid #F0F2F5;
        }

        .text {
            display: flex;
            width: calc(100% - 84px);
            padding: 10px;
            border: 1px solid #F0F2F5;
            border-radius: 5px;
            margin-right: 10px;
            font-size: 16px;
        }

        .button {
            padding: 10px 15px;
            width: 84px;
            background-color: #64737C;
            color: #FFFFFF;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

    </style>
</head>
<body>
    <div class="chat-container">
        <div class="title">Favorite food chatbot</div>
        <div class="messages" id="messages">
            {% for message in messages %}
                <div class="message {{message.owner}}">{{ message.message }}</div>
            {% endfor %}
        </div>
        <form id="userMessageForm" class="input-container" action="{% url 'bot:response' user_id %}" method="post">
        {% csrf_token %}
            <input class="text" name="message" type="text" id="userInput" placeholder="Type your message here...">
            <input class="button" type="submit" name="Send" value="Send" />
        </form>
    </div>
</body>
</html>

bot/templates/bot/register.html
<!-- This file is contains the HTML code that renders the page where the user can register himself/herself. -->

<!-- Reading the css style from the bot app static file -->
{% load static %}
<link rel="stylesheet" href="{% static 'bot/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Identify yourself</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            height: 100vh;
            background-color:#F0F2F5;
            background: #F0F2F5 url("../../static/bot/images/bot-icon.png") no-repeat;
            background-size: 300px;
            background-position-x: center;
            background-position-y: center;
        }

        .input-container {
            display: flex;
            flex-direction: column;
            padding: 10px;
            border-top: 1px solid #F0F2F5;
            gap: 24px;
        }

        .text {
            display: flex;
            width: 300px;
            padding: 10px;
            border: 1px solid #F0F2F5;
            border-radius: 5px;
            margin-right: 10px;
            font-size: 16px;
        }

        .button:enabled {
            padding: 10px 15px;
            width: 200px;
            background-color: #64737C;
            color: #FFFFFF;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .button:disabled {
            padding: 10px 15px;
            width: 200px;
            background-color: #E3E5E4;
            color: #929699;
            border: none;
            border-radius: 5px;
        }

    </style>
    <script>
        function toggleButton() {
            const textField = document.getElementById('userName');
            const submitButton = document.getElementById('submitButton');
            submitButton.disabled = textField.value.trim() === '';
        }
    </script>
</head>
<body>
    <form id="userRegistrationForm" class="input-container" action="{% url 'bot:start_conversation' %}" method="post">
    {% csrf_token %}
        <h2>What is your name?</h2>
        <!-- the values of the input divs will be accessible in the view called in the action through the request.POST dictionary by the value of its name parameter -->
        <input class="text" id="userName" type="text" name="userName" oninput="toggleButton()" placeholder="">
        <button class="button" id="submitButton" type="submit" disabled>Start conversation</button>
        <image/>
    </form>
</body>
</html>

bot/templates/bot/user_details.html
<!-- This file is contains the HTML code that renders the page with the details of a user. -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User details</title>
</head>
<body>
    <!-- title -->
     <!-- the user object is passed automatically by the Django Detail view -->
    <h1>Name: {{ user.name }}</h1>
    <p>Id: {{ user.id }}</p>
    <p>Favorite foods:</p>
    <ul>
        <!-- lists all the favorite foods -->
        {% for food in user.favorite_foods.all %}
            <li>{{ food.name }}</li>
        {% endfor %}
    </ul>
    <h3>Nutrition: {{ user.nutrition }}</h3>
</body>

bot/templates/bot/users.html
<!-- This file is contains the HTML code that renders the page with the list of users. It can be all the users or the ones from a specific nutrition type -->
<!-- The file is accessed through 2 different views: users and users/<nutrition> -->

<!-- Reading the css style from the bot app static file -->
{% load static %}
<link rel="stylesheet" href="{% static 'bot/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
</head>
<body>
    {% if current_users %}
        <!-- If we access the file through the users/nutrition view we want to show the nutrition we are looking at -->
        {% if nutrition %}
            <h1> {{nutrition}} Users</h1>
        {% endif %}
        <table>
            <thead>
                <tr>
                    <th>User name</th>
                    <th>Favorite foods</th>
                </tr>
            </thead>
            <tbody>
                <!-- 'current_users' is an element of the dictionary passed as 3rd parameter to the render function in the return of the views.py functions -->
                {% for user in current_users %}
                <tr>
                    <!-- the following href references the view with name 'user_details' from the app 'bot' and passes 'user.id' as a parameter after '/' -->
                    <td><a href="{% url 'bot:user_details' user.id %}">{{ user.name }}</a></td> 
                    <td>{{ user.favorite_foods.all }}</td> 
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <!-- If we access the file through the users/nutrition view we want to show the nutrition we are looking at -->
        {% if nutrition %}
            <h1>There are no {{nutrition}} users</h1>
        {% else %}
            <h1>There are no users</h1>
        {% endif %}
        
    {% endif %}
</body>